#!/usr/bin/bash

# shellcheck disable=SC2015
[[ -v __COMMON_SOURCED ]] && return || readonly __COMMON_SOURCED=true

# @VARIABLE: VERBOSITY
# @DESCRIPTION:
# The level of verbosity to apply to script output.
# * Level 0 (default): no additional verbosity; ideally quiet output
# * Level 1: `log()` statements produce output
# * Level 2: `set -v` is enabled
# * Level 3: `set -x` is enabled
VERBOSITY=0

# @FUNCTION: apply_verbosity
# @DESCRIPTION:
# Applies the effect of the `VERBOSITY` variable. Can be called repeatedly if
# `VERBOSITY` changes.
apply_verbosity() {
	if [[ "${VERBOSITY}" -ge 3 ]]; then
		set +v
		set -x
	elif [[ "${VERBOSITY}" -ge 2 ]]; then
		set +x
		set -v
	else
		set +xv
	fi
}

# @FUNCTION: die
# @USAGE: <message>
# @DESCRIPTION:
# Prints the given message to stderr and exits with an error code.
die() {
	printf '%s\n' "$@" 1>&2
	exit 1
}

# @FUNCTION: log
# @USAGE: <message>
# @DESCRIPTION:
# Prints the given message to stdout if `VERBOSE` is non-empty.
log() {
	[[ "${VERBOSITY}" -lt 1 ]] || printf '%s\n' "$@"
}

# vim: set tw=80 noet ts=2 sts=2 sw=2 #
